### PR TITLE
Update typings (errors on compilation)

### PR DESCRIPTION
**Pull request by Androz2091**
**Please describe the changes this PR makes and why it should be merged:**

The actually typings need to be updated because it causes an error during the compilation:
```
node_modules/wumpfetch/index.d.ts:35:7 - error TS7008: Member 'body' implicitly has an 'any' type.
body, json: any;
```
And this, for every modifications in this pull request. I used my patch-1 branch to do the compilation and it works perfectly.

**Status**
- [X] Code changes have been tested and there aren't any typos in it

**Semantic versioning classification:**
- [ ] This PR changes wumpfetch's core codebase (methods or parameters added)
  - [ ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [ ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

### CODE REVIEW

**Comment by auguwu** [comment]
👍

**Comment by ohlookitsderpy** [comment]
yes pls

**Comment by ohlookitsderpy** [comment]
@PassTheWessel is this going to get merged at some point?

**Comment by davidcralph** [comment]
as to when this gets put into 0.3.1 or something,

**Pull request merged**
